src/Entity/Recipes.php
<?php

namespace App\Entity;

use App\Repository\RecipesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RecipesRepository::class)]
class Recipes
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

     #[ORM\Column(type: 'datetime_immutable', nullable: true)]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private ?string $imagePath = null;

    #[ORM\ManyToOne(inversedBy: 'recipes')]
    private ?User $userId = null;

    #[ORM\OneToMany(targetEntity: Comments::class, mappedBy: 'recipeId')]
    private Collection $comments;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private ?string $username_user = null;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

   public function setCreatedAt(\DateTime $created_at): self
    {
        $this->created_at = \DateTimeImmutable::createFromMutable($created_at);

        return $this;
    }

    public function getImagePath(): ?string
    {
        return $this->imagePath;
    }

    public function setImagePath(?string $imagePath): self
    {
        $this->imagePath = $imagePath;

        return $this;
    }

    public function __toString()
    {
        return $this->getTitle(); // Vous pouvez utiliser le champ "title" ou un autre champ approprié
    }

    public function getUserId(): ?User
    {
        return $this->userId;
    }

    public function setUserId(?User $userId): static
    {
        $this->userId = $userId;

        return $this;
    }

    /**
     * @return Collection<int, Comments>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setRecipeId($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getRecipeId() === $this) {
                $comment->setRecipeId(null);
            }
        }

        return $this;
    }

    public function getUsernameUser(): ?string
    {
        return $this->username_user;
    }

    public function setUsernameUser(?string $username_user): self
    {
        $this->username_user = $username_user;

        return $this;
    }
}

src/Form/RecipesType.php
<?php

namespace App\Form;

use App\Entity\Recipes;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\DataTransformerInterface;
use App\Form\DateTimeToImmutableTransformer;

class RecipesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('content')
            ->add('created_at', DateTimeType::class, [
                'widget' => 'single_text',
                'label' => 'Date',
                'attr' => ['class' => 'form-control'],
            ])
            ->add('imagePath', FileType::class, [
                'label' => 'Image (JPEG, PNG)',
                'mapped' => false,
                'required' => false,
            ]);
           
        $builder->get('created_at')->addModelTransformer(new DateTimeToImmutableTransformer());
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Recipes::class,
        ]);
    }
}

src/Controller/RecipesController.php
<?php

namespace App\Controller;

use App\Entity\Recipes;
use App\Form\RecipesType;
use App\Repository\RecipesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Mime\MimeTypes;
use App\Entity\Comments;
use App\Form\CommentsType;

#[Route('/recipes')]
class RecipesController extends AbstractController
{
    #[Route('/', name: 'app_recipes_index', methods: ['GET'])]
    public function index(RecipesRepository $recipesRepository): Response
    {
        return $this->render('recipes/index.html.twig', [
            'recipes' => $recipesRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_recipes_new', methods: ['GET', 'POST'])]
public function new(Request $request, EntityManagerInterface $entityManager): Response
{
    $recipe = new Recipes();
    $form = $this->createForm(RecipesType::class, $recipe);
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
        $imageFile = $form['imagePath']->getData();

        if ($imageFile) {
            $mimeTypeGuesser = MimeTypes::getDefault();
            $extension = $mimeTypeGuesser->getExtensions($imageFile->getMimeType())[0] ?? 'bin';
            $newFilename = uniqid() . '.' . $extension;

            try {
                $imageFile->move(
                    $this->getParameter('images_directory'),
                    $newFilename
                );
                $recipe->setImagePath($newFilename);
            } catch (FileException $e) {
                // Gérer les exceptions liées au téléchargement du fichier
            }
        }

        // Récupérer l'utilisateur connecté
        $user = $this->getUser();

        // Assurer que l'utilisateur est connecté
        if ($user) {
            $recipe->setUserId($user);
            $recipe->setUsernameUser($user);
        }

        $entityManager->persist($recipe);
        $entityManager->flush();

        return $this->redirectToRoute('app_recipes_index', [], Response::HTTP_SEE_OTHER);
    }

    return $this->renderForm('recipes/new.html.twig', [
        'recipe' => $recipe,
        'form' => $form,
    ]);
}

    #[Route('/{id}', name: 'app_recipes_show', methods: ['GET'])]
    public function show(Recipes $recipe): Response
    {
        return $this->render('recipes/show.html.twig', [
            'recipe' => $recipe,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_recipes_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Recipes $recipe, EntityManagerInterface $entityManager): Response
{
    $form = $this->createForm(RecipesType::class, $recipe);
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
        $imageFile = $form['imagePath']->getData();

        // Vérifier s'il y a une nouvelle image
        if ($imageFile) {
            // Récupérer le chemin de l'ancienne image
            $oldImagePath = $recipe->getImagePath();

            // Supprimer l'ancienne image
            if ($oldImagePath) {
                $oldImagePath = $this->getParameter('images_directory') . '/' . $oldImagePath;
                if (file_exists($oldImagePath)) {
                    unlink($oldImagePath);
                }
            }

            // Uploader la nouvelle image
            $mimeTypeGuesser = MimeTypes::getDefault();
            $extension = $mimeTypeGuesser->getExtensions($imageFile->getMimeType())[0] ?? 'bin';
            $newFilename = uniqid() . '.' . $extension;

            try {
                $imageFile->move(
                    $this->getParameter('images_directory'),
                    $newFilename
                );
                $recipe->setImagePath($newFilename);
            } catch (FileException $e) {

            }
        }

        $entityManager->flush();

        return $this->redirectToRoute('app_recipes_index', [], Response::HTTP_SEE_OTHER);
    }

    return $this->renderForm('recipes/edit.html.twig', [
        'recipe' => $recipe,
        'form' => $form,
    ]);
}

    #[Route('/delete/{id}', name: 'app_recipes_delete', methods: ['POST'])]
public function delete(Request $request, Recipes $recipe, EntityManagerInterface $entityManager): Response
{
    if ($this->isCsrfTokenValid('delete'.$recipe->getId(), $request->request->get('_token'))) {
        // Récupérer le chemin complet de l'image
        $imagePath = $this->getParameter('images_directory') . '/' . $recipe->getImagePath();

        // Vérifier si le fichier image existe avant de le supprimer
        if (file_exists($imagePath)) {
            // Supprimer le fichier image
            unlink($imagePath);
        }

        // Supprimer l'entité post de la base de données
        $entityManager->remove($recipe);
        $entityManager->flush();
    }
    return $this->redirectToRoute('app_recipes_index', [], Response::HTTP_SEE_OTHER);

}


#[Route('/{id}/comment', name: 'app_recipes_comment', methods: ['GET', 'POST'])]
public function addComment(Request $request, Recipes $recipe, EntityManagerInterface $entityManager): Response
{
    $commentContent = $request->request->get('comment');

    if (!empty($commentContent)) {
        $user = $this->getUser();

        if ($user) {
            $comment = new Comments();
            $comment->setContent($commentContent);
            $comment->setUserId($user);
            $comment->setRecipeId($recipe);

            $entityManager->persist($comment);
            $entityManager->flush();


            return $this->redirectToRoute('app_recipes_show', ['id' => $recipe->getId()]);
        }
    }

    return $this->redirectToRoute('app_recipes_index');
}


#[Route('/comment/{id}/edit', name: 'app_comment_edit', methods: ['GET', 'POST'])]
public function editComment(Request $request, Comments $comment, EntityManagerInterface $entityManager): Response
{
    $recipeId = $comment->getRecipeId()->getId(); // Récupérer l'ID de la recette associée au commentaire

    $form = $this->createForm(CommentsType::class, $comment);
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
        $entityManager->flush();

        // Rediriger vers la route de visualisation de la recette avec l'ID de la recette
        return $this->redirectToRoute('app_recipes_show', ['id' => $recipeId]);
    }

    return $this->render('comment/edit.html.twig', [
        'comment' => $comment,
        'form' => $form->createView(),
    ]);
}


#[Route('/{id}', name: 'app_comment_confirm_delete', methods: ['POST'])]
    public function confirmDeleteComment(Request $request, Comments $comment, EntityManagerInterface $entityManager): Response
    {
            $recipeId = $comment->getRecipeId()->getId(); // Récupérer l'ID du post associé au commentaire

        if ($this->isCsrfTokenValid('delete'.$comment->getId(), $request->request->get('_token'))) {
            $entityManager->remove($comment);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_recipes_show', ['id' => $recipeId]);
    }


}

templates/recipes/_delete_form.html.twig
<form class="confirm-delete-form" method="post" action="{{ path('app_recipes_delete', {'id': recipe.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ recipe.id) }}">
    <button class="btn">Delete</button>
</form>

templates/recipes/_form.html.twig
{{ form_start(form, {'attr': {'class': 'my-4'}}) }}
<div class="form-group">
    {{ form_row(form.title, {'attr': {'class': 'form-control'}}) }}
</div>
<div class="form-group">
    {{ form_row(form.content, {'attr': {'class': 'form-control', 'rows': '5'}}) }}
</div>
<div class="form-group">
    {{ form_row(form.imagePath, {'attr': {'class': 'form-control'}}) }}
</div>
<button type="submit" class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/recipes/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Recipes{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <style>
        .card {
            margin-top: 20px;
        }

        .card-body {
            padding: 20px;
        }
    </style>
{% endblock %}

{% block body %}
    {% include 'partials/navbar.html.twig' %}

    <div class="container">
        <h1 class="text-center mt-4">Edit Recipe</h1>
        <div class="row justify-content-center mt-4">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body">
                        {{ form_start(form, {'attr': {'class': 'my-4'}}) }}
                        <div class="form-group">
                            {{ form_row(form.title, {'attr': {'class': 'form-control'}}) }}
                        </div>
                        <div class="form-group">
                            {{ form_row(form.content, {'attr': {'class': 'form-control', 'rows': '3'}}) }}
                        </div>
                        <div class="form-group">
                            {{ form_row(form.imagePath, {'attr': {'class': 'form-control'}}) }}
                        </div>
                        <div class="form-group">
                            {{ form_row(form.created_at, {'attr': {'class': 'form-control'}}) }}
                        </div>
                        
                        
                        <div class="form-group text-center">
                            <button type="submit" class="btn btn-primary mt-3">Edit</button>
                            <a href="{{ path('app_recipes_index') }}" class="btn btn-secondary mt-3">Back to list</a>
                        </div>
                        {{ form_end(form) }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <br/><br/>
    {% include 'partials/footer.html.twig' %}

{% endblock %}

templates/recipes/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Recipes index{% endblock %}

{% block body %}
{% include 'partials/navbar.html.twig' %}
<br/>
{% include 'partials/welcome.html.twig' %}

<div class="container text-center">
    <br/>

    <div class="row justify-content-center">
        {% for recipe in recipes %}
            <div class="col-md-4 mb-4">
                <div class="card">
                    {% if recipe.imagePath %}
                        <img src="{{ asset('uploads/images/' ~ recipe.imagePath) }}" class="card-img-top" alt="Image" style="max-width: 400px; max-height: 400px;">
                    {% else %}
                        <div class="no-image-placeholder">No image available</div>
                    {% endif %}
                    <div class="card-body">
                            <h5 class="card-title">{{ recipe.title }}</h5>
                            <p class="card-text">{{ recipe.content|split(' ')|slice(0, 41)|join(' ') }}</p>
                            <p class="card-text">Created by: {{ recipe.usernameUser  }}</p>
                                    <a href="{{ path('app_recipes_show', {'id': recipe.id}) }}" class="btn btn-primary">See more</a>

                            <p class="card-text"><small class="text-muted">{{ recipe.createdAt ? recipe.createdAt|date('Y-m-d H:i:s') : '' }}</small></p>
                    </div>
                </div>
            </div>
        {% else %}
            <p>No records found</p>
        {% endfor %}
    </div>
 
<br/>
</div>

{% include 'partials/footer.html.twig' %}

{% endblock %}

templates/recipes/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Recipe{% endblock %}


{% block stylesheets %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.0/css/bootstrap.min.css">
<style>
    .card {
        margin-top: 20px;
    }

    .card-body {
        padding: 20px;
    }
</style>
{% endblock %}

{% block body %}
{% include 'partials/navbar.html.twig' %}

<div class="container">
    <h1 class="text-center mt-4">Create New recipe</h1>
    <div class="row justify-content-center mt-4">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    {{ form_start(form, {'attr': {'class': 'my-4'}}) }}
                    <div class="form-group">
                        {{ form_row(form.title, {'attr': {'class': 'form-control'}}) }}
                    </div>
                    <div class="form-group">
                        {{ form_row(form.content, {'attr': {'class': 'form-control', 'rows': '3'}}) }}
                    </div>
                    <div class="form-group">
    {{ form_row(form.imagePath, {'attr': {'class': 'form-control'}}) }}
</div>
                    <div class="form-group">
                        {{ form_row(form.created_at, {'attr': {'class': 'form-control'}}) }}
                    </div>
                   
                    
                    <div class="form-group text-center">
                        <button type="submit" class="btn btn-primary mt-3">Create</button>
                        <a href="{{ path('app_recipes_index') }}" class="btn btn-secondary mt-3">Back to list</a>
                    </div>
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </div>

</div>
 <br/><br/>
 {% include 'partials/footer.html.twig' %}

{% endblock %}

templates/recipes/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Recipes{% endblock %}

{% block stylesheets %}

    <style>
        .card {
            width: 100%;
            margin: 0 auto;
            text-align: center;
            border: 1px solid #ccc;
            border-radius: 5px;
            padding: 10px;
            margin-top: 20px;
        }

        .card img {
            max-width: 100%;
            height: auto;
            max-height: 400px;
            display: block;
            margin: 0 auto;
            border-radius: 5px;
            margin-top: 10px;
        }

        .link {
            margin-top: 10px;
            padding: 5px 10px;
            background-color: #007bff;
            color: #fff;
            text-decoration: none !important;
            border-radius: 3px;
        }

        .link:hover {
            background-color: #007bff;
            color: #fff;
        }
        .delete-button {
            padding: 5px 10px;
            background-color: #dc3545;
            color: #fff;
            border: none;
            border-radius: 3px;
            cursor: pointer;
        }

       textarea {
        width: 100%;
        max-width: 400px;
        padding: 10px;
        margin: 10px 0;
        border: 1px solid #ccc;
        border-radius: 5px;
        resize: vertical; 
    }

    button.comment-button {
        margin-top: 10px;
        padding: 8px 16px;
        background-color: #28a745;
        color: #fff;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }

    button.comment-button:hover {
        background-color: #218838;
    }

    .comments-list {
        list-style-type: none;
        padding: 0;
    }

    .comment-item {
        background-color: #f9f9f9;
        border: 1px solid #ddd;
        border-radius: 5px;
        margin-bottom: 10px;
        padding: 10px;
    }

     .comment-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 5px;
    }

    .comment-author {
        font-weight: bold;
        color: #365899;
    }
    .edit-delete-links {
    display: flex;
    gap: 10px;
}

.edit-delete-links a {
    text-decoration: none;
    padding: 8px 16px;
    border: 1px solid #ccc;
    border-radius: 4px;
    background-color: green;
    color: white;
    font-weight: bold;
    text-align: center;
    display: inline-block;
    transition: background-color 0.3s, color 0.3s;
}

.edit-delete-links a:hover {
    background-color: #086f08;
    color: #fff;
}
.confirm-delete-form {
    display: inline-block;
}

.confirm-delete-form button {
    padding: 8px 16px;
    border: 1px solid #ccc;
    border-radius: 4px;
    background-color: red;
    color: white;
    font-weight: bold;
    text-align: center;
    display: inline-block;
    transition: background-color 0.3s, color 0.3s;
}

.confirm-delete-form button:hover {
    background-color: #dd1515;
    color: white;
}  

    .comment-body {
        font-size: 14px;
    }
    </style>
{% endblock %}

{% block body %}
    {% include 'partials/navbar.html.twig' %}
    <br/>
    <div class="container">
        <div class="card">
            <div class="card-body">
                {% if recipe.imagePath %}
                    <img src="{{ asset('uploads/images/' ~ recipe.imagePath) }}" alt="Image">
                {% else %}
                    No image available
                {% endif %}
            </div>
        </div>

        <table class="table">
            <tbody>
                <tr>
                    <h5 style="text-align: center;">{{ recipe.title }}</h5>
                </tr>
                <tr>
                    <td style="text-align: center;">{{ recipe.content }}</td>
                </tr>
                <tr>
                    <td style="text-align: center;">
                        <span style="font-weight: bold;">Created at : </span> {{ recipe.createdAt ? recipe.createdAt|date('Y-m-d H:i:s') : '' }}
                    </td>
                </tr>
            </tbody>
        </table>


        <div>
<div>
    <h3>Comments:</h3>
    <ul class="comments-list">
        {% for comment in recipe.comments %}
            <li class="comment-item">
                <div class="comment-header">
                    <strong class="comment-author">{{ comment.userId }}</strong>
                    <div class="edit-delete-links">
                        {% if comment.userId == app.user %}
                            <a href="{{ path('app_comment_edit', {'id': comment.id}) }}" class="edit">Edit</a>
                            {{ include('comment/confirm_delete.html.twig') }}
                        {% endif %}
                    </div>
                </div>
                <div class="comment-body">
                    <p>{{ comment.content }}</p>
                </div>
            </li>
        {% endfor %}
    </ul>
</div>


<form method="POST" action="{{ path('app_recipes_comment', {'id': recipe.id}) }}">
    <textarea class="form-control" name="comment" rows="10" placeholder="Enter your comment" style="width: 100%; max-width: 1200px; padding: 5px;"></textarea><br/>
    <button class="comment-button" style="margin-top: 10px;">comment</button>
</form>

<div style="text-align: center;">
    <div style="display: flex; justify-content: center; align-items: center;">
            <a href="{{ path('app_recipes_index') }}" class="btn btn-primary">back to list</a>&nbsp;&nbsp;

            {% if app.user == recipe.getUserId %}

        <a href="{{ path('app_recipes_edit', {'id': recipe.id}) }}" class="btn btn-primary">edit</a>&nbsp;&nbsp;
        <div style="align-self: center;">{{ include('recipes/_delete_form.html.twig') }}</div>
          {% endif %}
    </div>
</div>
<br/><br/>
    </div>
    {% include 'partials/footer.html.twig' %}
{% endblock %}